(()=>{'use strict';
const S=1,G=-1,MATE=100000000;
const V={P:100,L:300,N:320,S:450,G:550,B:800,R:950,K:20000};
const KJ={P:'歩',L:'香',N:'桂',S:'銀',G:'金',B:'角',R:'飛',K:'王','+P':'と','+L':'杏','+N':'圭','+S':'全','+B':'馬','+R':'龍'};
const BASE=k=>k[0]=='+'?k.slice(1):k,PROM=k=>k[0]=='+';
const xy=i=>[i%9,(i/9)|0],id=(x,y)=>y*9+x,inside=(x,y)=>x>=0&&x<9&&y>=0&&y<9;
let lastSearch={depth:0,nodes:0,ms:0,score:0},deadline=0,nodes=0,timed=false;
function fresh(){let b=Array(81).fill(null),back=['L','N','S','G','K','G','S','N','L'];for(let x=0;x<9;x++){b[x]={k:back[x],o:G};b[18+x]={k:'P',o:G};b[72+x]={k:back[x],o:S};b[54+x]={k:'P',o:S}}b[10]={k:'R',o:G};b[16]={k:'B',o:G};b[64]={k:'B',o:S};b[70]={k:'R',o:S};return{b,t:S,h:{1:{P:0,L:0,N:0,S:0,G:0,B:0,R:0},'-1':{P:0,L:0,N:0,S:0,G:0,B:0,R:0}},log:[],ply:0}}
function cp(s){return{b:s.b.map(p=>p?{...p}:null),t:s.t,h:{1:{...s.h[1]},'-1':{...s.h[-1]}},log:[...(s.log||[])],ply:s.ply||0}}
function label(p){return KJ[p.k]||KJ[BASE(p.k)]}
function goldDirs(){return[[0,-1],[-1,-1],[1,-1],[-1,0],[1,0],[0,1]]}
function stepDirs(p){let k=BASE(p.k);if(PROM(p.k)&&['P','L','N','S'].includes(k))return goldDirs();if(k==='K')return[[0,-1],[0,1],[-1,0],[1,0],[-1,-1],[1,-1],[-1,1],[1,1]];if(k==='G')return goldDirs();if(k==='S')return[[0,-1],[-1,-1],[1,-1],[-1,1],[1,1]];if(k==='N')return[[-1,-2],[1,-2]];if(k==='P')return[[0,-1]];if(PROM(p.k)&&k==='R')return[[-1,-1],[1,-1],[-1,1],[1,1]];if(PROM(p.k)&&k==='B')return[[0,-1],[0,1],[-1,0],[1,0]];return[]}
function slideDirs(p){let k=BASE(p.k);if(k==='R')return[[0,-1],[0,1],[-1,0],[1,0]];if(k==='B')return[[-1,-1],[1,-1],[-1,1],[1,1]];if(k==='L')return[[0,-1]];return[]}
function rawMoves(s,i){let p=s.b[i];if(!p)return[];let[x,y]=xy(i),out=[],sg=p.o;for(let[dx,dy]of stepDirs(p)){let nx=x+dx*sg,ny=y+dy*sg;if(!inside(nx,ny))continue;let q=s.b[id(nx,ny)];if(!q||q.o!==sg)out.push(id(nx,ny))}for(let[dx,dy]of slideDirs(p)){dx*=sg;dy*=sg;let nx=x+dx,ny=y+dy;while(inside(nx,ny)){let j=id(nx,ny),q=s.b[j];if(!q)out.push(j);else{if(q.o!==sg)out.push(j);break}nx+=dx;ny+=dy}}return out}
function kingPos(s,o){return s.b.findIndex(p=>p&&p.o===o&&BASE(p.k)==='K')}
function attacked(s,pos,by){for(let i=0;i<81;i++){let p=s.b[i];if(p&&p.o===by&&rawMoves(s,i).includes(pos))return true}return false}
function inCheck(s,o){let k=kingPos(s,o);return k<0||attacked(s,k,-o)}
function inZone(o,y){return o===S?y<=2:y>=6}
function promoteOptions(p,from,to){let k=BASE(p.k);if(PROM(p.k)||!['P','L','N','S','B','R'].includes(k))return[false];let fy=xy(from)[1],ty=xy(to)[1];if(!(inZone(p.o,fy)||inZone(p.o,ty)))return[false];let forced=(k==='P'||k==='L')&&(p.o===S?ty===0:ty===8)||k==='N'&&(p.o===S?ty<=1:ty>=7);return forced?[true]:[false,true]}
function apply(s,m){let n=cp(s),o=s.t;if(m.drop){n.h[o][m.k]--;n.b[m.to]={k:m.k,o}}else{let p={...n.b[m.from]},q=n.b[m.to];if(q){let bk=BASE(q.k);if(bk!=='K')n.h[o][bk]++}p.k=m.prom?'+'+BASE(p.k):p.k;n.b[m.to]=p;n.b[m.from]=null}n.t=-o;n.ply=(s.ply||0)+1;return n}
function normalMoves(s,o){let a=[];for(let i=0;i<81;i++){let p=s.b[i];if(!p||p.o!==o)continue;for(let t of rawMoves(s,i))for(let pr of promoteOptions(p,i,t)){let m={from:i,to:t,prom:pr},n=apply({...s,t:o},m);if(!inCheck(n,o))a.push(m)}}return a}
function nifu(s,o,x){for(let y=0;y<9;y++){let p=s.b[id(x,y)];if(p&&p.o===o&&p.k==='P')return true}return false}
function dropMoves(s,o){let a=[],h=s.h[o];for(let k of['P','L','N','S','G','B','R'])if(h[k]>0)for(let t=0;t<81;t++){if(s.b[t])continue;let[x,y]=xy(t);if(k==='P'&&nifu(s,o,x))continue;if((k==='P'||k==='L')&&(o===S?y===0:y===8))continue;if(k==='N'&&(o===S?y<=1:y>=7))continue;let m={drop:true,k,to:t},n=apply({...s,t:o},m);if(!inCheck(n,o))a.push(m)}return a}
function legal(s,o=s.t){return normalMoves(s,o).concat(dropMoves(s,o))}
function material(s,o){let z=0;for(let p of s.b)if(p)z+=(p.o===o?1:-1)*(V[BASE(p.k)]||0)+(PROM(p.k)?90*(p.o===o?1:-1):0);for(let k of['P','L','N','S','G','B','R'])z+=(s.h[o][k]-s.h[-o][k])*(V[k]||0);return z}
function attackMap(s,o){let a=new Uint8Array(81),mob=0;for(let i=0;i<81;i++){let p=s.b[i];if(!p||p.o!==o)continue;let ms=rawMoves(s,i);mob+=ms.length;for(let t of ms)if(a[t]<255)a[t]++}for(let k of['P','L','N','S','G','B','R'])if(s.h[o][k])mob+=Math.min(8,s.h[o][k]*2);return{a,mob}}
function kingSafetyFast(s,o,own,opp){let kp=kingPos(s,o);if(kp<0)return-5000;let[x,y]=xy(kp),score=0;for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++){if(!dx&&!dy)continue;let nx=x+dx,ny=y+dy;if(!inside(nx,ny))continue;let j=id(nx,ny),q=s.b[j];if(q&&q.o===o)score+=26;if(opp.a[j])score-=34*opp.a[j];else score+=8}score-=opp.a[kp]*110;let home=o===S?8:0;score-=Math.abs(y-home)*8;return score}
function hangingRiskFast(s,o,own,opp){let risk=0;for(let i=0;i<81;i++){let p=s.b[i];if(!p||p.o!==o||BASE(p.k)==='K')continue;let a=opp.a[i];if(!a)continue;let d=own.a[i],v=V[BASE(p.k)]||0;risk+=d?Math.min(v*.22,a*35):v*.72}return risk}
function hangingRisk(s,o){let own=attackMap(s,o),opp=attackMap(s,-o);return hangingRiskFast(s,o,own,opp)}
function kingPressureFast(s,o,am){let ek=kingPos(s,-o);if(ek<0)return 5000;let[ex,ey]=xy(ek),score=am.a[ek]*90;for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++){if(!dx&&!dy)continue;let x=ex+dx,y=ey+dy;if(!inside(x,y))continue;let d=Math.max(Math.abs(dx),Math.abs(dy)),n=am.a[id(x,y)];if(d===1)score+=n*20;else if(d===2)score+=n*6}return score}
function development(s,o){let sc=0;for(let i=0;i<81;i++){let p=s.b[i];if(!p||p.o!==o)continue;let[,y]=xy(i),k=BASE(p.k);if(['S','G','B','R'].includes(k)){let adv=o===S?7-y:y-1;if(adv>0)sc+=Math.min(adv,3)*8}if(PROM(p.k))sc+=25}return sc}
function openingBonus(s,o,opening){let sc=0,kp=kingPos(s,o),rp=s.b.findIndex(p=>p&&p.o===o&&BASE(p.k)==='R');if(kp>=0){let[kx]=xy(kp);if(opening.includes('矢倉')||opening.includes('雁木'))sc+=Math.abs(kx-4)*7;if(opening.includes('穴熊'))sc+=Math.abs(kx-4)*11}if(rp>=0){let[rx]=xy(rp);if(opening.includes('四間'))sc+=(o===S?Math.abs(rx-5):Math.abs(rx-3))<2?35:0;if(opening.includes('三間')||opening.includes('石田'))sc+=(o===S?Math.abs(rx-6):Math.abs(rx-2))<2?35:0;if(opening.includes('中飛車'))sc+=Math.abs(rx-4)<2?35:0}return sc}
function cfgFor(c){let r=c.r,depth=r>=2400?4:r>=1800?3:r>=1450?2:1,time=r>=3000?1500:r>=2850?1350:r>=2700?1250:r>=2600?1200:r>=2500?1050:r>=2400?900:r>=2200?620:r>=2000?470:r>=1800?340:r>=1600?230:r>=1450?170:100,root=r>=3000?18:r>=2850?16:r>=2700?15:r>=2600?14:r>=2500?13:r>=2400?12:r>=2200?14:r>=1900?13:r>=1600?12:10,branch=r>=3000?9:r>=2850?8:r>=2700?8:r>=2600?7:r>=2400?7:r>=2200?8:r>=1900?7:r>=1600?6:5,error=r>=2500?0:r>=2200?.008:r>=1900?.02:r>=1700?.045:r>=1500?.08:.16;let w={mat:1,safe:1,hang:1,mob:.55,press:.55,dev:.4,end:.6,open:.35};const set=x=>Object.assign(w,x);switch(c.kind){case'master':set({mat:1.15,safe:1.25,hang:1.35,mob:.72,press:.78,dev:.55,end:1.05,open:.48});break;case'speed':set({safe:.84,hang:.9,mob:1.05,press:1.05,dev:.9,end:.72,open:.55});break;case'universal':set({safe:1.1,hang:1.15,mob:.68,press:.75,dev:.5,end:.95,open:.45});break;case'defense':set({mat:1.18,safe:1.65,hang:1.8,mob:.42,press:.38,dev:.35,end:.82,open:.6});break;case'recovery':set({mat:1.15,safe:1.38,hang:1.45,mob:.62,press:.55,dev:.48,end:.9,open:.55});break;case'precision':set({mat:1.2,safe:1.18,hang:1.5,mob:.55,press:.65,end:.9});break;case'attack':set({mat:.95,safe:.82,hang:.82,mob:.72,press:1.35,dev:.72,end:.95});break;case'furibisha':set({safe:1.18,mob:.78,press:.7,dev:.62,open:.9});break;case'chaos':set({safe:.78,hang:.78,mob:.9,press:1.25});break;case'mobility':set({safe:.9,mob:1.15,press:.82,dev:.78});break;case'flex':set({safe:1,mob:.88,press:.7,dev:.62});break;case'trick':set({safe:.8,hang:.8,mob:.95,press:1.05});break;case'strategy':set({safe:1.18,hang:1.28,mob:.72,press:.8,open:.75,end:.95});break;case'power':set({mat:1.05,safe:.9,hang:.95,mob:.7,press:1.12});break;case'counter':set({safe:1.35,hang:1.35,mob:.55,press:.95,end:1});break;case'patient':set({mat:1.15,safe:1.4,hang:1.35,mob:.45,press:.48,end:1.05});break;case'endgame':set({safe:1.1,hang:1.2,mob:.62,press:.9,end:1.55});break}return{rating:r,depth,time,root,branch,error,w,opening:c.opening,kind:c.kind}}
function evaluate(s,root,cfg){let phase=Math.min(1,(s.ply||0)/70),rm=attackMap(s,root),om=attackMap(s,-root),mat=material(s,root),safe=kingSafetyFast(s,root,rm,om)-kingSafetyFast(s,-root,om,rm),hang=hangingRiskFast(s,-root,om,rm)-hangingRiskFast(s,root,rm,om),mob=rm.mob-om.mob,press=kingPressureFast(s,root,rm)-kingPressureFast(s,-root,om),dev=development(s,root)-development(s,-root),op=openingBonus(s,root,cfg.opening)-openingBonus(s,-root,cfg.opening),score=mat*cfg.w.mat+safe*cfg.w.safe+hang*cfg.w.hang+mob*cfg.w.mob+press*cfg.w.press+dev*cfg.w.dev+op*cfg.w.open;score+=phase*cfg.w.end*(press*.45+mat*.08);return score}
function moveHeuristic(s,m,side,cfg){let sc=0,q=s.b[m.to],p=m.drop?{k:m.k,o:side}:s.b[m.from];if(q)sc+=(V[BASE(q.k)]||0)*8-(V[BASE(p.k)]||0)*.7;if(m.prom)sc+=520;if(m.drop)sc+=45;let n=apply({...s,t:side},m);if(inCheck(n,-side))sc+=620;if(attacked(n,m.to,-side)&&BASE(p.k)!=='K')sc-=(V[BASE(p.k)]||0)*2.8*cfg.w.hang;if(cfg.kind==='defense'&&BASE(p.k)==='K')sc+=120;return sc}
function ordered(s,moves,side,cfg,limit){let a=moves.map(m=>({m,h:moveHeuristic(s,m,side,cfg)}));a.sort((x,y)=>y.h-x.h);return a.slice(0,Math.min(limit,a.length)).map(x=>x.m)}
function tacticalMoves(s,cfg,limit){let side=s.t,a=[];for(let m of legal(s,side)){let q=s.b[m.to];if(q||m.prom){a.push(m);continue}let n=apply(s,m);if(inCheck(n,-side))a.push(m)}return ordered(s,a,side,cfg,limit)}
function search(s,depth,alpha,beta,root,cfg,ply){nodes++;if((nodes&127)===0&&performance.now()>deadline){timed=true;return evaluate(s,root,cfg)}let lm=legal(s,s.t);if(!lm.length)return inCheck(s,s.t)?(s.t===root?-MATE+ply:MATE-ply):0;if(depth<=0){let stand=evaluate(s,root,cfg);if(ply<6){let t=tacticalMoves(s,cfg,Math.max(3,Math.floor(cfg.branch/2)));if(t.length){let best=s.t===root?-Infinity:Infinity;for(let m of t){let v=search(apply(s,m),-1,alpha,beta,root,cfg,ply+1);if(s.t===root){if(v>best)best=v;if(best>alpha)alpha=best}else{if(v<best)best=v;if(best<beta)beta=best}if(beta<=alpha||timed)break}if(Number.isFinite(best))return s.t===root?Math.max(stand,best):Math.min(stand,best)}}return stand}let lim=depth>=3?cfg.branch:Math.min(cfg.branch+3,18),ms=ordered(s,lm,s.t,cfg,lim);if(s.t===root){let best=-Infinity;for(let m of ms){let v=search(apply(s,m),depth-1,alpha,beta,root,cfg,ply+1);if(v>best)best=v;if(best>alpha)alpha=best;if(beta<=alpha||timed)break}return best}else{let best=Infinity;for(let m of ms){let v=search(apply(s,m),depth-1,alpha,beta,root,cfg,ply+1);if(v<best)best=v;if(best<beta)beta=best;if(beta<=alpha||timed)break}return best}}
function choose(s,cfg,side){let start=performance.now();deadline=start+cfg.time;nodes=0;timed=false;let lm=legal(s,side);if(!lm.length)return null;let roots=ordered(s,lm,side,cfg,cfg.root),bestMove=roots[0],bestScore=-Infinity,doneDepth=0,ranked=[];for(let d=1;d<=cfg.depth;d++){let cur=[],localBest=-Infinity,localMove=bestMove;for(let m of roots){if(performance.now()>deadline){timed=true;break}let n=apply({...s,t:side},m),reply=legal(n,-side);if(!reply.length&&inCheck(n,-side)){lastSearch={depth:d,nodes,ms:Math.round(performance.now()-start),score:MATE};return m}let v=search(n,d-1,-Infinity,Infinity,side,cfg,1);cur.push({m,v});if(v>localBest){localBest=v;localMove=m}if(timed)break}if(!timed&&cur.length){doneDepth=d;bestMove=localMove;bestScore=localBest;ranked=cur.sort((a,b)=>b.v-a.v)}else if(!doneDepth&&cur.length){ranked=cur.sort((a,b)=>b.v-a.v);bestMove=ranked[0].m;bestScore=ranked[0].v}if(timed)break;roots=cur.sort((a,b)=>b.v-a.v).map(x=>x.m)}if(cfg.error>0&&ranked.length>1&&Math.random()<cfg.error){let span=Math.min(ranked.length,cfg.rating<1500?5:cfg.rating<1800?3:2);bestMove=ranked[1+Math.floor(Math.random()*(span-1))].m}lastSearch={depth:doneDepth||1,nodes,ms:Math.round(performance.now()-start),score:Math.round(bestScore)};return bestMove}
function moveText(m,o,state){if(m.drop)return(o===S?'▲':'△')+KJ[m.k]+'打';let[x,y]=xy(m.to),p=state.b[m.from];return(o===S?'▲':'△')+(9-x)+(y+1)+KJ[m.prom?('+'+BASE(p?.k||'P')):BASE(p?.k||'P')]+(m.prom?'成':'')}
window.ShogiEngine={S,G,V,KJ,BASE,xy,id,fresh,cp,label,legal,apply,inCheck,material,hangingRisk,cfgFor,evaluate,choose,moveText,getLastSearch:()=>({...lastSearch})};
})();