(()=>{'use strict';
const E=window.ShogiEngine;if(!E)return;
const oldCfg=E.cfgFor.bind(E), oldChoose=E.choose.bind(E), MATE=1e8;
const FIXED={"みつき":0,"みっちゃん":1,"あき王":2,"おにまま":3,"まま":4};
function cfgFor(c){const b=oldCfg(c),mobile=/iPhone|iPad|iPod|Android|Silk/i.test(navigator.userAgent);let d,t,q,ix=FIXED[c.name];if(ix===0){d=9;t=mobile?1500:2350;q=6}else if(ix===1){d=8;t=mobile?1200:1900;q=5}else if(ix===2){d=8;t=mobile?1020:1620;q=5}else if(ix===3){d=7;t=mobile?880:1400;q=4}else if(ix===4){d=7;t=mobile?780:1250;q=4}else if(c.r<1350){d=2;t=100;q=1}else if(c.r<1550){d=3;t=180;q=2}else if(c.r<1750){d=4;t=280;q=2}else if(c.r<1950){d=5;t=430;q=3}else if(c.r<2150){d=6;t=670;q=3}else if(c.r<2300){d=7;t=880;q=4}else{d=8;t=mobile?1100:1600;q=5}return{...b,depth:d,time:t,q,maxDepth:d,strong212:true}}
const BASE=E.BASE,V=E.V,xy=E.xy;let deadline=0,nodes=0,qnodes=0,ttHits=0,last={depth:0,nodes:0,qnodes:0,ms:0,score:0,ttHits:0},TT=new Map(),killers=[],hist=new Map();
function key(s){let b=s.b.map(p=>p?(p.o>0?'s':'g')+p.k:'_').join('');let h=o=>['P','L','N','S','G','B','R'].map(k=>k+(s.h[o][k]||0)).join('');return(s.t>0?'S':'G')+'|'+b+'|'+h(1)+'|'+h(-1)}
function usi(m){if(m.drop)return m.k+'*'+m.to;return m.from+'-'+m.to+(m.prom?'+':'')}
function hscore(s,m,ply=0){let sc=0,q=s.b[m.to],p=m.drop?{k:m.k}:s.b[m.from];if(q)sc+=200000+(V[BASE(q.k)]||0)*20-(V[BASE(p?.k||'P')]||0);if(m.prom)sc+=18000;if(m.drop)sc+=300;let u=usi(m);if(killers[ply]?.includes(u))sc+=9000;sc+=hist.get(s.t+':'+u)||0;try{let n=E.apply(s,m);if(E.inCheck(n,-s.t))sc+=12000}catch{}return sc}
function order(s,lm,ply=0,limit=99){return lm.map(m=>({m,s:hscore(s,m,ply)})).sort((a,b)=>b.s-a.s).slice(0,limit).map(x=>x.m)}
function checkTime(){if(((nodes+qnodes)&127)===0&&performance.now()>deadline)throw 1}
function qsearch(s,a,b,root,cfg,ply,left){qnodes++;checkTime();let lm=E.legal(s,s.t);if(!lm.length)return E.inCheck(s,s.t)?(s.t===root?-MATE+ply:MATE-ply):0;let stand=E.evaluate(s,root,cfg),max=s.t===root;if(left<=0)return stand;if(max){if(stand>=b)return stand;if(stand>a)a=stand}else{if(stand<=a)return stand;if(stand<b)b=stand}let tactical=[];for(const m of lm){let cap=s.b[m.to];if(cap||m.prom){tactical.push(m);continue}let n=E.apply(s,m);if(E.inCheck(n,n.t))tactical.push(m)}if(!tactical.length)return stand;tactical=order(s,tactical,ply,14);let best=stand;for(const m of tactical){let v=qsearch(E.apply(s,m),a,b,root,cfg,ply+1,left-1);if(max){if(v>best)best=v;if(best>a)a=best}else{if(v<best)best=v;if(best<b)b=best}if(b<=a)break}return best}
function search(s,d,a,b,root,cfg,ply){nodes++;checkTime();if(d<=0)return qsearch(s,a,b,root,cfg,ply,cfg.q||3);let k=key(s),ent=TT.get(k),oa=a,ob=b;if(ent&&ent.d>=d){ttHits++;if(ent.f==='E')return ent.v;if(ent.f==='L')a=Math.max(a,ent.v);else if(ent.f==='U')b=Math.min(b,ent.v);if(a>=b)return ent.v}let lm=E.legal(s,s.t);if(!lm.length)return E.inCheck(s,s.t)?(s.t===root?-MATE+ply:MATE-ply):0;let lim=d>=4?Math.max(7,Math.min(12,cfg.root||12)):d>=2?Math.max(9,Math.min(16,(cfg.root||12)+2)):20;lm=order(s,lm,ply,lim);let max=s.t===root,best=max?-Infinity:Infinity,bm=null;for(const m of lm){let v=search(E.apply(s,m),d-1,a,b,root,cfg,ply+1);if(max){if(v>best){best=v;bm=m}if(best>a)a=best}else{if(v<best){best=v;bm=m}if(best<b)b=best}if(b<=a){let u=usi(m);if(!killers[ply])killers[ply]=[];if(!killers[ply].includes(u))killers[ply]=[u,...killers[ply]].slice(0,2);hist.set(s.t+':'+u,(hist.get(s.t+':'+u)||0)+d*d*10);break}}let f=best<=oa?'U':best>=ob?'L':'E';if(TT.size>18000){let n=0;for(const x of TT.keys()){TT.delete(x);if(++n>3000)break}}TT.set(k,{d,v:best,f,b:bm?usi(bm):null});return best}
function choose(s,cfg,side){let start=performance.now(),lm=E.legal(s,side);if(!lm.length)return null;for(const m of lm){let n=E.apply({...s,t:side},m);if(!E.legal(n,-side).length&&E.inCheck(n,-side)){last={depth:1,nodes:1,qnodes:0,ms:Math.round(performance.now()-start),score:MATE,ttHits:0,mate1:true};return m}}
deadline=start+cfg.time;nodes=qnodes=ttHits=0;TT=new Map();killers=[];hist=new Map();let roots=order(s,lm,0,Math.min(lm.length,cfg.rating>=2700?22:cfg.rating>=2400?18:16)),best=roots[0],bestScore=-Infinity,done=0,ranked=[];for(let d=1;d<=cfg.depth;d++){try{let cur=[];for(const m of roots){checkTime();let v=search(E.apply({...s,t:side},m),d-1,-Infinity,Infinity,side,cfg,1);cur.push({m,v})}cur.sort((a,b)=>b.v-a.v);if(cur.length){ranked=cur;best=cur[0].m;bestScore=cur[0].v;done=d;roots=cur.map(x=>x.m)}}catch(e){break}}
if(cfg.error>0&&ranked.length>1&&Math.random()<cfg.error){let n=cfg.rating<1400?4:cfg.rating<1600?3:2;best=ranked[Math.min(ranked.length-1,1+Math.floor(Math.random()*Math.max(1,n-1)))].m}last={depth:done||1,nodes,qnodes,ms:Math.round(performance.now()-start),score:Math.round(bestScore),ttHits,strong:true};return best}
E.cfgFor=cfgFor;E.choose=choose;E.getLastSearch=()=>({...last});
const D=[
{start:['よろしくね。でも、本気でいくよ。','今日は負けないよ。','準備はいい？ ちゃんと見ててね。'],normal:['まだまだ、これからだよ。','落ち着いていこう。','次の一手が大事だね。','盤面全体を見ていこう。'],winning:['流れはこっちかな。','見えてきたよ、勝ち筋が。','ここからは正確にいくよ。'],losing:['まだ終わってないよ。','ここから立て直す。','逆転の筋を探すよ。'],critical:['ここ、正念場だね。','深く読むよ。','一手も間違えられないね。'],think:['ちょっと深く読むね。','先の先まで見てみる。'],check:['王手だよ。ここから読んでね。','玉の逃げ道、ちゃんと見えてる？'],win:['ありがとう。いい勝負だったよ。','うれしいな。また指そう。'],loss:['……強かった。また挑戦するね。','今回は負けたけど、次は負けないよ。']},
{start:['あそぶー！！','しょーぎ、するするー！','いくよー！ えいえいおー！'],normal:['るんばー！','みつきーっく！','うどんさんたべたい。','ぺんぎんさんちにいきたいー','じゃんぷ、じゃんぷ！','にゃんびー','じゅーすちょうだい。'],winning:['やったー！','いいかんじー！','つよいでしょー！'],losing:['あれれー？','なんでー？','たいへんだー！'],critical:['大人なのに本気でやるの・・・、ぐすん','ままーだっこしてーー','たすけてー！'],think:['うーん、うーん。','かんがえちゅー！'],check:['おうてー！','にげてにげてー！'],win:['かったー！！','みっちゃんつよーい！'],loss:['くやしいー！','もういっかいするー！']},
{start:['よろしくお願いします。','落ち着いていきましょう。','丁寧に指していきます。'],normal:['ここはよく考えたいですね。','一手ずつ整理していきましょう。','盤面全体を見ておきたいですね。'],winning:['少しよくなってきましたね。','この流れは活かしたいです。','無理せず積み重ねましょう。'],losing:['まだ逆転の余地はあります。','ここからが大事ですね。','受けを正確にしたいです。'],critical:['慎重にいきましょう。','ここは踏ん張りどころです。','一番危ない筋を消しましょう。'],think:['ここは少し読みを入れます。','終盤まで見通してみます。'],check:['王手です。応手を正確に。','玉の安全を最優先にしてください。'],win:['ありがとうございました。','最後まで集中できました。'],loss:['参りました。','見事でした。']},
{start:['さあ、ちゃんと考えて指しなさい。','手を抜かずにいくわよ。','半端な気持ちじゃ勝てないわよ。'],normal:['そこ、よく見なさい。','雑に指すと痛い目を見るわよ。','まだ甘いわね。','一手一手に責任を持ちなさい。'],winning:['あまいわね。','その隙は見逃さないわ。','しっかり詰めていくわよ。','逃がさないわよ。'],losing:['まだよ、ここから立て直すわ。','そんな程度で終わらないわ。','受けの強さを見せる時ね。'],critical:['ここは本気でいくわよ。','絶対に崩れないわ。','ここを耐えれば流れは変わるわ。'],think:['黙って待ちなさい。読んでるところよ。','ここは軽く指せないわね。','全部確認してから指すわ。'],check:['王手よ。さあ、どう受けるの？','逃げ道まで読んで指しなさい。'],win:['勝ちは勝ちよ。','また鍛えてあげるわ。'],loss:['今回は負けを認めるわ。','次はもっと厳しくいくわよ。']},
{start:['よろしくね。','あわてずにいこうね。','いい時間にしましょうね。'],normal:['どう進めるのがいいかな。','ちょっと整理してみよう。','まだまだこれから。','急がなくても大丈夫だよ。'],winning:['少しずつよくなってるね。','このまま丁寧にいこう。','いい形ができてきたかも。'],losing:['だいじょうぶ、まだいけるよ。','ここから立て直そう。','あきらめるのはまだ早いよ。'],critical:['まずは一番危ないところから。','受けて落ち着こう。','ここは慎重にね。'],think:['ちょっと考えるね。','一番いい手を探してるよ。'],check:['王手だね。落ち着いて受けよう。','玉の逃げ道を確認してね。'],win:['ありがとう。よくがんばったね。','またいっしょに指そう。'],loss:['今回は残念だったね。','またがんばろう。']}
];
let prev=Array(5).fill('');function pick(a,i){let b=a.filter(x=>x!==prev[i]);if(!b.length)b=a;let x=b[Math.floor(Math.random()*b.length)];prev[i]=x;return x}
function charIndex(){let n=(document.getElementById('oppName')?.textContent||'').split(/\s|　/)[0];return FIXED[n]??-1}
function mood(i){let status=document.getElementById('status')?.textContent||'';if(status.includes('考えています'))return'think';if(status.includes('あなたの勝ち'))return'loss';if(status.includes('の勝ちです'))return'win';try{let st=window.AI_SHOGI_DEBUG?.getState?.();if(st&&E.inCheck(st,1))return'check';let sc=window.AI_SHOGI_DEBUG?.eval?.(-1,i);if(Number.isFinite(sc)){if(sc>650)return'winning';if(sc<-650)return'critical';if(sc<-220)return'losing'}}catch{}if(status.includes('先手です'))return'start';return'normal'}
function speak(){let i=charIndex();if(i<0||!D[i])return;let m=mood(i),pool=D[i][m]||D[i].normal,text=pick(pool,i),a=document.getElementById('speech'),b=document.getElementById('fspeech');if(a)a.textContent=text;if(b)b.textContent=text}
window.addEventListener('load',()=>{window.AI_SHOGI_BUILD='2.12.0-strong-search-dialogue';let targets=['status','oppName'].map(id=>document.getElementById(id)).filter(Boolean);let ob=new MutationObserver(()=>queueMicrotask(speak));targets.forEach(x=>ob.observe(x,{childList:true,subtree:true,characterData:true}));speak();});
})();